# Classification Model Selection

# For Large Datasets

In [13]:
# Required Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [14]:
# importing the dataset
ds = pd.read_csv("Social_Network_Ads.csv", nrows=200)


# Data Preprocessing

In [15]:
# preprocessing if required


In [16]:
# splitting into dependent and independent variables
X = ds.iloc[:, 2:4].values
y = ds.iloc[:, -1].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [17]:
# y dataset
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [18]:
# Feature scaling
sc = StandardScaler()
SX = sc.fit_transform(X)
SX

array([[-1.52370992, -1.34479807],
       [ 0.62804284, -1.31234638],
       [-0.58231809, -0.56595749],
       [-0.44783354, -0.11163382],
       [-1.52370992,  0.50494831],
       [-0.44783354, -0.07918213],
       [-0.44783354,  0.76456184],
       [ 0.22458919,  2.90637344],
       [-0.71680264, -0.8904744 ],
       [ 0.62804284,  0.14797971],
       [-0.58231809,  0.63475507],
       [-0.58231809, -0.27389227],
       [-1.38922537,  0.82946522],
       [ 0.22458919, -1.37724976],
       [-1.65819447,  0.69965846],
       [-0.17886445,  0.63475507],
       [ 2.2418574 , -1.15008793],
       [ 1.97288831, -1.11763623],
       [ 2.10737285, -1.05273285],
       [ 2.37634195, -1.02028116],
       [ 1.97288831, -1.247443  ],
       [ 2.2418574 , -0.37124734],
       [ 2.37634195, -0.63086087],
       [ 1.97288831, -1.247443  ],
       [ 2.10737285, -1.21499131],
       [ 2.2418574 , -1.31234638],
       [ 2.5108265 , -1.05273285],
       [ 2.2418574 , -0.98782947],
       [-0.17886445,

# Without Feature Scaling

In [19]:
# Model Tuner
model_params = {
        "svc":{"model":SVC(),
                "params":{"C":[1.5, 2.0 , 2.5, 3.5, 4],
                          "kernel":["rbf","poly","linear"]},
                          
            },
        "Random_Forest":{"model":RandomForestClassifier(),
                        "params":{"n_estimators":[10, 25, 50, 75, 100, 150],
                                  "criterion":["gini","entropy"]}
                        },
        "Logistic_Regression":{"model":LogisticRegression(),
                               "params":{"C":[1.5, 2.0 , 2.5, 3.5, 4]}
                               },
        "Gaussian_NB":{"model":GaussianNB(),
                        "params":{}
                        },
         "Bernoulli_NB":{"model":BernoulliNB(),
                        "params":{}
                        },
         "K_NN":{"model":KNeighborsClassifier(),
                        "params":{"n_neighbors":[5, 7, 9, 11]}
                        },
         "DecisionTree_Classifier":{"model":DecisionTreeClassifier(),
                        "params":{"criterion":["gini", "entropy"]}
                        }
                } 
mul_params ={ "Multinomial_NB":{"model":MultinomialNB(),
                        "params":{}
                        }
            }               


In [20]:
# To run model_params we need for loop.
score = []
for model_name, mp in model_params.items():
    classifier = RandomizedSearchCV(mp["model"], mp["params"],
                              cv = 5, return_train_score=False, n_iter = 3)
    classifier.fit(X, y)
    score.append({"model":model_name,
                  "best_score":classifier.best_score_,
                  "best_params" : classifier.best_params_})

for model_name, mp in mul_params.items():
    classifier = RandomizedSearchCV(mp["model"], mp["params"],
                              cv = 5, return_train_score=False, n_iter = 3)
    classifier.fit(X, y)
    score.append({"model":model_name,
                  "best_score":classifier.best_score_,
                  "best_params" : classifier.best_params_})

df = pd.DataFrame(score, columns = ["model", "best_score", "best_params"])

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 2 is smaller than n_iter=3. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive search

#The Best Model Is:(Without Feature Scaling)

In [21]:

df[["model", "best_params","best_score"]][df.best_score == df.best_score.max()]


model                                best_params  best_score
1  Random_Forest  {'n_estimators': 25, 'criterion': 'gini'}        0.94

# Other model Performances

In [22]:
df.sort_values("best_score", ascending = False)

model  ...                                best_params
1            Random_Forest  ...  {'n_estimators': 25, 'criterion': 'gini'}
6  DecisionTree_Classifier  ...                   {'criterion': 'entropy'}
3              Gaussian_NB  ...                                         {}
0                      svc  ...               {'kernel': 'poly', 'C': 1.5}
5                     K_NN  ...                         {'n_neighbors': 7}
2      Logistic_Regression  ...                                 {'C': 1.5}
4             Bernoulli_NB  ...                                         {}
7           Multinomial_NB  ...                                         {}

[8 rows x 3 columns]

# self increasing model efficiency by tuning

In [23]:
#cross_val_score()

# With Feature Scaling


In [24]:
# To run model_params we need for loop.
score1 = []
for model_name, mp in model_params.items():
    classifier1 = RandomizedSearchCV(mp["model"], mp["params"],
                              cv = 5, return_train_score=False, n_iter = 3)
    classifier1.fit(SX, y)
    score1.append({"model":model_name,
                  "best_score":classifier1.best_score_,
                  "best_params" : classifier1.best_params_})
    
df1 = pd.DataFrame(score1, columns = ["model", "best_score", "best_params"])

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 2 is smaller than n_iter=3. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


# The Best Model is: (With Feature Scaling)

In [25]:

df1[["model", "best_params","best_score"]][df1.best_score == df1.best_score.max()]


model                   best_params  best_score
0   svc  {'kernel': 'poly', 'C': 2.5}       0.945

# Other Model performances!

In [26]:
df1.sort_values("best_score", ascending = False)

model  ...                                best_params
0                      svc  ...               {'kernel': 'poly', 'C': 2.5}
5                     K_NN  ...                        {'n_neighbors': 11}
1            Random_Forest  ...  {'n_estimators': 50, 'criterion': 'gini'}
6  DecisionTree_Classifier  ...                   {'criterion': 'entropy'}
3              Gaussian_NB  ...                                         {}
2      Logistic_Regression  ...                                 {'C': 1.5}
4             Bernoulli_NB  ...                                         {}

[7 rows x 3 columns]

# self increasing model efficiency by tuning


In [27]:
# cross_val_score()